channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=24.0
- pip:
  - mlflow==3.7.0
  - cloudpickle==3.1.2
  - numpy==1.26.2
  - pandas==2.2.1
  - psutil==7.1.3
  - scikit-learn==1.6.1
  - scipy==1.14.1
  - xgboost==3.1.2
name: mlflow-env
